# Generated by Django 5.0.7 on 2024-07-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['placed_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='post_amount',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
