# Generated by Django 5.0.7 on 2024-08-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_user_post_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_address',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_post',
            new_name='user',
        ),
    ]
