# Generated by Django 5.0.7 on 2024-08-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rename_user_address_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
