# Generated by Django 5.0.7 on 2024-08-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_post_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
