# Generated by Django 5.0.7 on 2024-08-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_user_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post_amount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
