# Generated by Django 5.0.7 on 2024-08-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_alter_user_post_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
