# Generated by Django 5.0.7 on 2024-08-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_rename_name_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post_amount',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateField(),
        ),
    ]
