# Generated by Django 5.0.7 on 2024-08-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
