# Generated by Django 5.0.7 on 2024-08-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='playground.address'),
        ),
    ]
