# Generated by Django 5.0.7 on 2024-08-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='playground.post'),
        ),
    ]
